{% set name = "lintsampler" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lintsampler-{{ version }}.tar.gz
  sha256: 3ca52b0ba5014b7ec1e780cfb74ed0dbb0672a7b9ed3be2e9df705ec6debf329

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.6
    - numpy >=1.17,<2.0

test:
  imports:
    - lintsampler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aneeshnaik/lintsampler/
  summary: Efficient random sampling via linear interpolation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aneeshnaik
