{% set name = "lintsampler" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lintsampler-{{ version }}.tar.gz
  sha256: e42f47bf868f9eacdcaa2e236a6be6ec498a22caab3d8a5eb2ae414bef27fb6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.6
    - numpy >=1.17,<2.0

test:
  imports:
    - lintsampler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aneeshnaik/lintsampler/
  summary: Efficient random sampling via linear interpolation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aneeshnaik
